# Generated by Django 2.1.5 on 2019-11-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
